version: '3'
services:
  app:
    image: oceanize/flask_app:latest
    container_name: flask_app
    restart: unless-stopped
    labels:
      project: "flask"
      day: "9 Sep 2019"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      API_USER: ${API_USER}
      API_PASSWORD: ${API_PASSWORD}
    volumes:
      - ./rest:/rest
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - "5000:5000"

  mysql:
    container_name: flask_mysql
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    labels:
      project: "flask"
      day: "9 Sep 2019"
    ports:
      - "33006:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    container_name: flask_phpmyadmin
    restart: unless-stopped
    labels:
      project: "flask"
      day: "9 Sep 2019"
    ports:
      - "5010:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

volumes:
  mysql-data:
    driver: local